### ISSUE TITLE
Latest Version of the PLIST

### ISSUE THREAD

**Issue by corytrese** [Dave1482/CodeSnippets#1]
<dict>
        <key>i386</key>
        <string>32-bit Simulator</string>
        <key>x86_64</key>
        <string>64-bit Simulator</string>
        <key>iPad1,1</key>
        <string>iPad</string>
        <key>iPad2,1</key>
        <string>iPad 2</string>
        <key>iPad2,2</key>
        <string>iPad 2</string>
        <key>iPad2,3</key>
        <string>iPad 2</string>
        <key>iPad2,4</key>
        <string>iPad 2</string>
        <key>iPad2,5</key>
        <string>iPad Mini 1</string>
        <key>iPad2,6</key>
        <string>iPad Mini 1</string>
        <key>iPad2,7</key>
        <string>iPad Mini 1</string>
        <key>iPad3,1</key>
        <string>iPad 3rd Gen</string>
        <key>iPad3,2</key>
        <string>iPad 3rd Gen</string>
        <key>iPad3,3</key>
        <string>iPad 3rd Gen</string>
        <key>iPad3,4</key>
        <string>iPad 4th Gen</string>
        <key>iPad3,5</key>
        <string>iPad 4th Gen</string>
        <key>iPad3,6</key>
        <string>iPad 4th Gen</string>
        <key>iPad4,1</key>
        <string>iPad Air</string>
        <key>iPad4,2</key>
        <string>iPad Air</string>
        <key>iPad4,3</key>
        <string>iPad Air</string>
        <key>iPad4,4</key>
        <string>iPad Mini 2</string>
        <key>iPad4,5</key>
        <string>iPad Mini 2</string>
        <key>iPad4,6</key>
        <string>iPad Mini 2</string>
        <key>iPad4,7</key>
        <string>iPad Mini 3</string>
        <key>iPad4,8</key>
        <string>iPad Mini 3</string>
        <key>iPad4,9</key>
        <string>iPad Mini 3</string>
        <key>iPad5,1</key>
        <string>iPad Mini 4</string>
        <key>iPad5,2</key>
        <string>iPad Mini 4</string>
        <key>iPad5,3</key>
        <string>iPad Air 2</string>
        <key>iPad5,4</key>
        <string>iPad Air 2</string>
        <key>iPad6,3</key>
        <string>iPad Pro 9.7 inch</string>
        <key>iPad6,4</key>
        <string>iPad Pro 9.7 inch</string>
        <key>iPad6,7</key>
        <string>iPad Pro 12.9 inch</string>
        <key>iPad6,8</key>
        <string>iPad Pro 12.9 inch</string>
        <key>iPad7,1</key>
        <string>iPad Pro 12.9 inch 2nd Gen</string>
        <key>iPad7,11</key>
        <string>iPad 7th Gen</string>
        <key>iPad7,12</key>
        <string>iPad 7th Gen</string>
        <key>iPad7,2</key>
        <string>iPad Pro 12.9 inch 2nd Gen</string>
        <key>iPad7,3</key>
        <string>iPad Pro 10.5 inch</string>
        <key>iPad7,4</key>
        <string>iPad Pro 10.5 inch</string>
        <key>iPad7,5</key>
        <string>iPad 6th Gen</string>
        <key>iPad7,6</key>
        <string>iPad 6th Gen</string>
        <key>iPad8,1</key>
        <string>iPad Pro 11 inch</string>
        <key>iPad8,2</key>
        <string>iPad Pro 11 inch</string>
        <key>iPad8,3</key>
        <string>iPad Pro 11 inch</string>
        <key>iPad8,4</key>
        <string>iPad Pro 11 inch</string>
        <key>iPad8,5</key>
        <string>iPad Pro 12.9 inch 3rd Gen</string>
        <key>iPad8,6</key>
        <string>iPad Pro 12.9 inch 3rd Gen</string>
        <key>iPad8,7</key>
        <string>iPad Pro 12.9 inch 3rd Gen</string>
        <key>iPad8,8</key>
        <string>iPad Pro 12.9 inch 3rd Gen</string>
        <key>iPad8,9</key>
        <string>iPad Pro 11 inch 2nd Gen</string>
        <key>iPad8,10</key>
        <string>iPad Pro 11 inch 2nd Gen</string>
        <key>iPad8,11</key>
        <string>iPad Pro 12.9 inch 4th Gen</string>
        <key>iPad8,12</key>
        <string>iPad Pro 12.9 inch 4th Gen</string>
        <key>iPad11,1</key>
        <string>iPad Mini 5</string>
        <key>iPad11,2</key>
        <string>iPad Mini 5</string>
        <key>iPad11,3</key>
        <string>iPad Air 3</string>
        <key>iPad11,4</key>
        <string>iPad Air 3</string>
        <key>iPad11,6</key>
        <string>iPad (8th Gen)</string>
        <key>iPad11,7</key>
        <string>iPad (8th Gen)</string>        
        <key>iPad13,1</key>
        <string>iPad Air 4</string>
        <key>iPad13,2</key>
        <string>iPad Air 4</string>      
        <key>iPad13,11</key>
        <string>iPad Pro (12.9 5th Gen)</string>
        <key>iPad13,10</key>
        <string>iPad Pro (12.9 5th Gen)</string>
        <key>iPad13,9</key>
        <string>iPad Pro (12.9 5th Gen)</string>
        <key>iPad13,8</key>
        <string>iPad Pro (12.9 5th Gen)</string>
        <key>iPad13,4</key>
        <string>iPad Pro (11 3rd Gen)</string>
        <key>iPad13,5</key>
        <string>iPad Pro (11 3rd Gen)</string>
        <key>iPad13,6</key>
        <string>iPad Pro (11 3rd Gen)</string>
        <key>iPad13,7</key>
        <string>iPad Pro (11 3rd Gen)</string>
        <key>iPad14,1</key>
        <string>iPad mini 6</string>
        <key>iPad14,2</key>
        <string>iPad mini 6</string>
        <key>iPad12,1</key>
        <string>iPad (9th Gen)</string>
        <key>iPad12,2</key>
        <string>iPad (9th Gen)</string>
        <key>iPad13,13</key>
        <string>iPad Air 5</string>
        <key>iPad13,16</key>
        <string>iPad Air 5</string>
        <key>iPhone1,1</key>
        <string>iPhone</string>
        <key>iPhone1,2</key>
        <string>iPhone 3G</string>
        <key>iPhone2,1</key>
        <string>iPhone 3GS</string>
        <key>iPhone3,1</key>
        <string>iPhone 4</string>
        <key>iPhone3,2</key>
        <string>iPhone 4</string>
        <key>iPhone3,3</key>
        <string>iPhone 4</string>
        <key>iPhone4,1</key>
        <string>iPhone 4S</string>
        <key>iPhone5,1</key>
        <string>iPhone 5 model A1428</string>
        <key>iPhone5,2</key>
        <string>iPhone 5 model A1429</string>
        <key>iPhone5,3</key>
        <string>iPhone 5C</string>
        <key>iPhone5,4</key>
        <string>iPhone 5C</string>
        <key>iPhone6,1</key>
        <string>iPhone 5S</string>
        <key>iPhone6,2</key>
        <string>iPhone 5S</string>
        <key>iPhone7,1</key>
        <string>iPhone 6 Plus</string>
        <key>iPhone7,2</key>
        <string>iPhone 6</string>
        <key>iPhone8,1</key>
        <string>iPhone 6S</string>
        <key>iPhone8,2</key>
        <string>iPhone 6S Plus</string>
        <key>iPhone8,4</key>
        <string>iPhone SE (1st Gen.)</string>
        <key>iPhone9,1</key>
        <string>iPhone 7</string>
        <key>iPhone9,2</key>
        <string>iPhone 7 Plus</string>
        <key>iPhone9,3</key>
        <string>iPhone 7</string>
        <key>iPhone9,4</key>
        <string>iPhone 7 Plus</string>
        <key>iPhone10,1</key>
        <string>iPhone 8</string>
        <key>iPhone10,2</key>
        <string>iPhone 8 Plus</string>
        <key>iPhone10,3</key>
        <string>iPhone X</string>
        <key>iPhone10,4</key>
        <string>iPhone 8</string>
        <key>iPhone10,5</key>
        <string>iPhone 8 Plus</string>
        <key>iPhone10,6</key>
        <string>iPhone X</string>
        <key>iPhone11,2</key>
        <string>iPhone XS</string>
        <key>iPhone11,4</key>
        <string>iPhone XS Max</string>
        <key>iPhone11,6</key>
        <string>iPhone XS Max</string>
        <key>iPhone11,8</key>
        <string>iPhone XR</string>
        <key>iPhone12,1</key>
        <string>iPhone 11</string>
        <key>iPhone12,3</key>
        <string>iPhone 11 Pro</string>
        <key>iPhone12,5</key>
        <string>iPhone 11 Pro Max</string>
        <key>iPhone12,8</key>
        <string>iPhone SE (2nd Gen.)</string>
        <key>iPhone13,2</key>
        <string>iPhone 12</string>
        <key>iPhone13,3</key>
        <string>iPhone 12 Pro</string>
        <key>iPhone13,4</key>
        <string>iPhone 12 Pro Max</string>
        <key>iPhone13,1</key>
        <string>iPhone 12 Mini</string>
        <key>iPhone14,5</key>
        <string>iPhone 13</string>
        <key>iPhone14,2</key>
        <string>iPhone 13 Pro</string>
        <key>iPhone14,3</key>
        <string>iPhone 13 Pro Max</string>
        <key>iPhone14,4</key>
        <string>iPhone 13 mini</string>
        <key>iPhone14,6	</key>
        <string>iPhone SE (3rd generation)</string>
        <key>iPhone14,7</key>
        <string>iPhone 14</string>
        <key>iPhone14,8</key>
        <string>iPhone 14 Plus</string>
        <key>iPhone15,2	</key>
        <string>iPhone 14 Pro</string>
        <key>iPhone15,3</key>
        <string>iPhone 14 Pro Max</string>        
        <key>iPod1,1</key>
        <string>iPod Touch 1st Gen</string>
        <key>iPod2,1</key>
        <string>iPod Touch 2nd Gen</string>
        <key>iPod3,1</key>
        <string>iPod Touch 3rd Gen</string>
        <key>iPod4,1</key>
        <string>iPod Touch 4th Gen</string>
        <key>iPod5,1</key>
        <string>iPod Touch 5th Gen</string>
        <key>iPod7,1</key>
        <string>iPod Touch 6th Gen</string>
        <key>iPod9,1</key>
        <string>iPod Touch 7th Gen</string>
    </dict>

**Comment by corytrese** [comment]
maybe i should have made a pull request? hope this isn't annoying

**Comment by Dave1482** [comment]
Yea pull request lol

**Comment by corytrese** [comment]
this was better than just posting it on Twitter tho ;)
